@api = http://localhost:3000/companies


### Get all companies
{{api}}

### get a single company
{{api}}/1

### get company Jobs
{{api}}/1/Jobs

### get a single 
{{api}}/lancing.application@gmail.com/companyContact

