@api = http://localhost:4000/freelancers


### Get all freelancers
{{api}}


### get a single freelancer
{{api}}/1


### get projects for a freelancer
{{api}}/1/projects


### delete a single freelancer
DELETE {{api}}/20


### update freelancer
PUT {{api}}/23
Content-Type: application/json

{
  "phone": "21354603956"
}



### create a new freelancer
POST {{api}}
Content-Type: application/json

{
  "fname": "peter",
  "lname": "parker",
  "email": "peter@gmail.com",
  "address": "123 avengers drive",
  "city": "New York",
  "country": "United States",
  "dob": "2000-01-01",
  "phone": "6832453564",
  "country_code": "1"
}