@api = http://localhost:3000/freelancers


### Get all freelancers
{{api}}


### get a single freelancer by id
{{api}}/1

### get a single freelancer by email
{{api}}/email/james.bell@slu.edu


### get projects for a freelancer
{{api}}/1/projects


### delete a single freelancer
DELETE {{api}}/49


### update freelancer
PUT {{api}}/23
Content-Type: application/json

{
  "phone": "21354603957"
}



### create a new freelancer
POST {{api}}
Content-Type: application/json

{
  "fname": "peter",
  "lname": "parker",
  "email": "peter@gmail.com",
  "address": "123 avengers drive",
  "city": "New York",
  "country": "United States",
  "dob": "2000-01-01",
  "phone": "6832453564",
  "country_code": "1"
}

################################
GET {{api}}/skills/1
