@api = http://localhost:4000/Application



### get Applications
GET {{api}}

### Apply for job by freelancer id


POST {{api}}
Content-Type: application/json

{
    "freelancer_id": "1",
    "job_id": "1",
    "status_id": "1"
}