@api = http://localhost:3000

{{api}}/loginFreelancer/lucas.zoilo@slu.edu
Content-Type: application/json

{
    "password": "123456"
}
###
{{api}}/loginCompany/john.steward@gamil.com
Content-Type: application/json

{
    "password": "123456"
}
###
PUT {{api}}/updateFreelancerPassword/lucas.zoilo@slu.edu
Content-Type: application/json

{
    "passwordOld": "654321",
    "passwordNew": "123456"
}

###
PUT {{api}}/updateCompanyPassword/john.steward@gamil.com
Content-Type: application/json

{
    "passwordOld": "000000",
    "passwordNew": "123456"
}
### 
POST {{api}}/register/Freelancer
Content-Type: application/json

{
    "fname": "Jose Fidel",
    "lname": "Paredes",
    "email": "josefidel.paredes@slu.edu", 
    "address": "Ronda de las Sirenas 33",
    "city": "Madrid", 
    "country": "Spain",
    "dob": "1988-11-03", 
    "phone": "689874492",
    "country_code": "34",
    "password": "123456"
}

###
POST {{api}}/register/Company
content-type: application/json

{
    "Company_name":"Starbucks",
    "address":"Starbucks Street",
    "email":"lucia.henry@gmail.com",
    "Contact_name":"Lucia Henry", 
    "phone":"643060578",
    "country_code":"34", 
    "password":"123456"
}